# 確率の概念  

ここでは，確率を計算するにあたって必要な順列と組み合わせについて紹介していきます．
離散的な事象について，単純に確率を計算するには数え上げをする必要があります．すなわち，
考え得る全ての場合を重複が無いように数え上げなければ行けません．確率が「同様に確からしい」
とするならば，多くの場合確率は

$$
  \frac{1}{\text{全ての場合の数}}
$$

と定義されるでしょう．

## 順列と組み合わせによる数え上げ  


### 順列：Permutation
まず，$n!$という記号は階乗を表し$n! = n \times (n-1) \times (n-2) \times \cdots \times 2 \times 1$である．ただしここでは$n \in \N$とする．

::: {.definition name="順列"}
$n$個の相異なるものの順列を$n!$と定義する．
:::

さらに，応用として$n$人全員を並ばせるのではなく，$r(\leq n)$人だけ並ばせることを考えます．これは順列の計算において$r$個掛けるだけということになるので

$$
  n \times (n-1) \times (n-2) \times \cdots \times (n - r +2) \times (n - r + 1)
$$

となります．これを$_nP_r$と書き，階乗を用いて表せば次のようになります．

$$
\begin{equation}
  _n P_r = \frac{n!}{(n-r)!}
  (\#eq:def-permutaion)
\end{equation}
$$

つぎに，$n$個のうち同じものとみなせるケースを考えてみましょう．例えば，赤玉と青玉がそれぞれ$n_r$個，$n_b$個ずつあると考えます．
このとき赤玉同士，青玉同士は区別しない並べ方は何通りあるでしょうか？このような場合は次の手順で考えていきます．

1. まず先ほどの順列と同じように，全てを区別して何通りの並べ方があるか考える
2. 本来区別せずに数えるべきものが何通りあったかを考える
3. 1と2から求めたかった場合の数を計算する

1については赤玉と青玉の数の合計$n = n_r + n_b$個から，$n! = (n_r + n_b)!$となります．2について考えていきましょう．1では赤玉同士も全て区別して数え上げていますが，本来は区別したくありません．
考えてみると，赤玉と青玉それぞれの並べ方は$n_r!, n_b!$通りあることがわかります．そして，赤玉・青玉は1の考え方では$n_r!, n_b!$個ずつ重複して数え上げを行っていることがわかります．以上のことから3としては

$$
  \frac{n!}{n_r! n_b!}
$$
とすれば，求めたい数になることがわかりました．

更にこれ一般化し，全体の中に$m$個種類のものが$n_1, \ldots, n_m$個ずつあるとき，同じ種類のものを区別しないで並べる方法は$n=\sum_{i=1}^{m} n_i$として

$$
\begin{equation}
  \frac{n!}{\Pi_{i=1}^m n_i!}
  (\#eq:def-generalized-permutation)
\end{equation}
$$
となります．

通常の順列は，上記のケースにおいて$m$種類のものがそれぞれ1個ずつしかないという特別な場合と考えることもできます．


### 組み合わせ：Combination

次に$n$個のものから$r$個を選ぶことを考えます．このとき選び方は何通りあるでしょうか？まず，記号としてこれを$n \choose r$や$_nCr$と表します．順列を応用して考えると，$_nPr$という操作は次のように分解できます．

1. $n$個のものから$r$個を選ぶ（$={_n}C_r$）
2. $r$個を全て並べる（$=r!$）

すなわち

$$
  _n P_r = {_n C_r} \cdot r!
$$
と書き下せます．あとはこの式を$_nC_r$について表し直せば

$$
\begin{equation}
  _n C_r = \frac{_nP_r}{r!} = \frac{n!}{(n-r)!r!}
  (\#eq:def-combination)
\end{equation}
$$
を得ることができました．

### 演習問題  

次の問いに回答してください．

::: {.exercise name="順列と組み合わせの基本"} 
次の問いに回答してください．

1. 6人を右から一列に並ぶときの並び方は何通りあるか．
2. 6人から3人を一列に並ばせる．このとき並び方は何通りあるか．
3. 6人から2人を選ぶ組み合わせは何通りあるか．
4. 6人を2チームに分け，更に2つのチームを横に並べる方法は何通りあるか．この時チーム内の並び方は無視して良い．
5. 丸いテーブルに6人が座る時，その並びは何通りあるか．  
:::


::: {.exercise name="誕生日問題"}
25人の異なる人がいるとして，少なくとも同じ誕生日の人が二人はいるようなケースは何通りあるでしょうか．また，それと全ての25人の誕生日の組み合わせの場合の数との比を取って，同じ誕生日の人がいることが珍しいことかどうか確かめてみてください．
計算においては，2月29日は考慮しないものとし，誕生日は365日のいずれかであるものとします．
:::


## 集合と確率  

ここでは集合と確率について考えていきます．集合については「集合と論理」でその定義や基本的な性質を紹介しました．ですのでまずは確率について考えていきましょう．確率を集合に対して定義します．すなわち全体集合$\Omega$の要素$e_i(i=1,2,\ldots,k)$に対して，各要素$e_i$に対応する値$P(e_i)$が与えられていて，更に次を満たすとします．

$$
\begin{equation}
  \begin{aligned}
  & 0 \leq P(e_i) \leq 1, \hspace{5mm} i=1,2,\ldots,k \\
  & \sum_{i=1}^{k} P(e_i) = 1
  \end{aligned}
  (\#eq:prob-axiom)
\end{equation}
$$

このとき，集合$A \in \Omega$のに対して，その確率$P(A)$を次のように定義します．

$$
\begin{equation}
  P(A) = \sum_{e_i \in A} P(e_i)
  (\#eq:subset-prob)
\end{equation}
$$


ただし，空集合$\emptyset$に対する確率は$0$とします．つまり$P(\emptyset) = 0$です．以上より，任意の集合$A$に対して$0 \leq P(A) \leq 1$であり，$P(\Omega) = 1$であることがわかります．以降は，確率が定義された集合を**事象**と呼びます．


::: {.exercise}
面が$1 \sim 6$まであるサイコロについて，全体集合$\Omega = \{1,2,3,4,5,6 \}$として，\@ref(eq:prob-axiom)を満たすような$P(e_i)$をそれぞれ定めてください．ただし，全ての$e_i$に対して，$P(e_i) = 1/6$とする方法以外で考えてください．
:::

### 集合の演算と確率  

先ほど定義した確率と集合の関係から，集合演算の結果の確率についても自然に次式を得ることができます．集合$A,B \in \Omega$に対してその和事象$A \cup B$の確率は

$$
\begin{equation}
\begin{aligned}
  P(A \cup B) &= \sum_{e_i \in A \cup B} P(e_i) \\
  &= \sum_{e_i \in A} P(e_i) + \sum_{e_i \in B} - \sum_{e_i \in A \cap B} P(e_i) \\
  &= P(A) + P(B) - P(A \cap B)
\end{aligned}
(\#eq:prob-union)
\end{equation}
$$

となります．これを$\bigcup_{i \in I} A_i$に対して一般化して，あらかじめ$i \neq j$に対して$A_i \cap A_j = \emptyset$であるような集合族$\mathcal A = \{ A_i \}_{i \in I}$を考えます（すなわち$\sqcup_{i \in I} A_i = \Omega$です），その確率$P(\mathcal A)$は次のようになります．


$$
\begin{equation}
  P(\mathcal A) =  P \left( \bigcup_{i \in I} A_i  \right) = \sum_{i \in I}P(A_i)
(\#eq:generalized-prob-union)
\end{equation}
$$

ただし$I$は添え字集合とします．

### 余事象とその確率  

ある事象の補集合を余事象と言います．すなわち$A^{c} = \Omega \mysetminus A$です．明らかに$\Omega = A \cup A^c$かつ$A \cup A^c = \emptyset$ですから，


$$
\begin{equation}
  P(A^c) = P(\Omega) - P(A) = 1 - P(A)
(\#eq:prob-compliment)
\end{equation}
$$

であることがわかります．

::: {.exercise name="余事象の応用"}
A君とB君がジャンケンを勝ち負けが着くまで行い，これを100回繰り返すとします．この時，A君が少なくとも2勝する確率を求めてください．ただし，A君もB君もジャンケンに勝つ確率は共に$1/2$とします．
:::


### 条件付確率  

ここでは，条件付確率（conditional probability）というものを考えていきます．現実的な状況として，我々は何かしらの条件の下での確率を考えることは数多くあります．例えば，身体的な性別毎に寿命が違うことが挙げられます．これは，**性別**という条件の下で人は何歳まで生きるのかという確率を考えていると捉えていることもできるでしょう．

これまでの議論と同様に確率を集合に対して定義するという立場を取ります．いまある一つの事象$B \subset \Omega$を考えます．そして，$\Omega$の取り方によって$B$の確率がどのように変わるのかを考えていきます．いま$^\forall e_i$に対して$0 \leq P(e_i) \leq 1$かつ$P(\Omega) = 1$となるように確率が定められているわけですから，これをそのまま使って$B = \Omega_B$という新たな全体集合を定めた上で$A \subset \Omega_B$という部分集合を考えます（$\Omega$の部分集合$B=\Omega_B$のさらなる部分集合です）．また，$\Omega$上に定められた確率と$\Omega_B$上に定められた確率を明確に区別するために以降はそれぞれ$P$と$P_B$という記号を使うことにします．

さて，$P_B$をこれまで述べてきた確率の定義を満たすように定めたいわけですが

$$
P_B(A) = \sum_{e_i \in A} P(e_i)
$$

としてしまうと，$A \neq \Omega$であれば$P_B(B) = P_B(\Omega_B) = \sum_{e_i \in B} P(e_i) = P(B) < 1$となり，全体集合に対する確率が1未満になってしまいます．そこで，$^\forall e_i, e_j \in \Omega_B$に対して

$$
  \frac{P_B(e_i)}{P_B(e_j)} = \frac{P(e_i)}{P(e_j)}
$$
を満たすようにします．これは結局

$$
  P_B(e_i) = \frac{P_B(e_j)}{P(e_j)} P(e_i) = c P(e_i)
$$

と表せるので元の全体集合$\Omega$上で定義された$e_i$に対する確率$P(e_i)$に定数$c$を掛けているとみなせます．さらに$P_B(\Omega_B) = 1$となるようにしなければ行けないので

$$
  \sum_{e_i \in \Omega_B} P_B(e_i) = c \sum_{e_i \in B} P(e_i) = 1
$$

となることがわかります．これより

$$
c = \frac{1}{\sum_{e_i \in \Omega_B} P_B(e_i)} = \frac{1}{P(\Omega_B)}
$$

と設定してあげれば良いこともわかりました．$cP(\Omega_B) = 1$であるので，$^{\forall}e_i \in \Omega_B$について$0 \leq P_B(e_i) \leq 1$を満たすこともわかります．故に$A \subset \Omega_B ( = B)$について確率は

$$
  P_B(A) = \sum_{e_i \in A} P_B(e_i) = \frac{1}{P(B)} \sum_{e_i \in A} P(e_i) = \frac{P(A)}{P(\Omega_B)}
$$

という様に，元々$\Omega$上で定められた確率を新たな全体集合$\Omega_B$の確率で割ってあげれば良いことになります．

このような操作を，「事象$B$を与えた時の$A$の条件付確率」と呼び$P(A|B)$と表します．つまり，全体集合$\Omega$の$^{\forall}B \subset \Omega$とその部分集合$A \subset B$に関して

$$
  P(A|B) = \frac{P(A)}{P(B)}
$$
となります．$A \not\subset B$である場合も$A' = A \cap B$に対して条件確率を考えれば良いです．
以上の議論を踏まえて，条件付確率を次のように定義します．

::: {.definition name="条件付確率"}
全体集合$\Omega$について，$^\forall A, B \subset \Omega, P(B) > 0$に対して，事象$B$を与えたときの$A$の条件確率を次式で定義します．

$$
\begin{equation}
  P(A|B) = \frac{P(A \cap B)}{P(B)}
(\#eq:def-conditional-probability)
\end{equation}
$$
:::

定義から直ちに$A,B$が互いに疎であれば$P(A|B)=0$となることが分かります．
また，同様に定義から直ちに次の定理を導くことができます．

::: {.theorem name="乗法公式"}
条件付確率の定義より$P(A \cap B)$について次式が成り立ちます．

$$
\begin{equation}
  P(A \cap B) = P(B)P(A|B)  
  (\#eq:prob-multi)
\end{equation}
$$

:::

条件付確率と関連した概念として，独立を定義します．

::: {.definition name="独立"}
全体集合$\Omega$について，$A, B \subset \Omega$を考えます．この時，次式が成り立つ時$A$と$B$は独立であると言います．

$$
  P(A|B) = P(A)
$$

:::

独立とは条件付けした事象が，もう一方の事象の確率に影響しないことを意味しています．

::: {.exercise name="条件付確率と独立"}

白玉を2個，黒玉を4個入れた袋があります．この袋から順番に2個の玉を無作為に取り出すとします．

1. 最初に取り出した玉を元に戻さずに次の球を取り出します．この時，最初の玉が白玉である事象を$A$，次の玉が黒玉である事象を$B$とします．$P(A \cap B)$を求めてください．さらに，これらの事象が独立であるかどうか検証してください．
1. 最初に取り出した玉を元に戻してから次の球を取り出します．この時，最初の玉が白玉である事象を$A$，次の玉が黒玉である事象を$B$とします．$P(A \cap B)$を求めてください．さらに，これらの事象が独立であるかどうか検証してください．

:::

### ベイズの定理  

ここでは，ベイズの定理の導出・応用について紹介します．

まず事象$A$と$k$個の事象$B_1, \ldots, B_k$を考えます．ただし，$\{ A \cap B_i \}_{i=1}^{k}$は$A$の分割であるとします．つまり

$$
  A = \sqcup A \cap B_i, \hspace{5mm} i=1,2,\ldots,k
$$

とします．この時条件付確率の定義と乗法公式を適用すれば

$$
\begin{equation}
\begin{aligned}
  P(B_1|A) &= \frac{P(A \cap B_1)}{P(A)} \\
  &= \frac{P(A \cap B_1)}{\sum_{i=1}^{k} P(A \cap B_i)} \\
  &= \frac{P(A|B_1)P(B)}{\sum_{i=1}^k P(A|B_i)P(B_i)}
\end{aligned}
(\#eq:derivation-of-bayse-theorem)
\end{equation}
$$

を得ます．上記の式変形は最初に$\{ B_i \}_{i=1}^{k}$を$A$の分割となるように上手く取っておいたことで可能になっています．これを一般的に表現したものが次のベイズの定理です．

::: {.theorem name="ベイズの定理"}
いま$A \cap B_i, \hspace{3mm} i=1,\ldots,k$が$A$の分割であるとき，全ての$i(1 \leq i \leq k)$について，次式が成り立ちます．


\begin{equation}

P(B_i|A) = \frac{P(A|B_i)P(B_i)}{\sum_{i=1}^{k} P(A|B_i)P(B_i)}

(\#eq:bayse-theorem)
\end{equation}

:::

::: {.example name="検査の誤判定"}

新型コロナウイルスの感染の有無を調べる検査$X$を考えましょう．この検査$X$についてはあらかじめ次のことが分かっています．

1. 実際にコロナウイルスに感染している人に対しては95%の精度で陽性となる
2. コロナウイルスに感染していない人に対しては90%の精度で陰性となる

また，日本人のうち0.01%の人がコロナウイルスに感染しているとします．このときある人が検査$X$を受けて陽性と判定されました．この人が本当にコロナウイルスに感染している確率を求めてみましょう．

まず分かっていることを整理し，ベイズの定理の仮定と照らし合わせていきましょう．

- 知りたいのは「検査$X$で陽性」という条件のもとで，「本当に感染している確率」ですから事象$A$を「検査$X$で陽性」として，事象$B_1$を「本当に感染していること」としましょう．こうすれば，求めたい確率を$P(B_1|A)$と表せます．
- 「検査$X$で陰性」というのは「検査$X$で陽性」という事象の余事象と考えられますので，これを$A^c$と表せます．
- 次に，$\{ B_i \}_{i=1}^{k}$は$A$の分割となるようにとる必要がありますが，事象$B_2$は「本当に感染していないこと」とすれば，あまりなく網羅できることが分かります．

次に，分かっている確率を数式に落とし込んでいきましょう．

- 「実際にコロナウイルスに感染している人に対しては95%で陽性」は$P(A|B_1) = 0.95$と表せます．
- $P(A|B_1) = 0.95$より$P(A|B_2) = 1 - P(A|B_1) = 0.05$となります．
- 「コロナウイルスに感染していない人に対しては90%で陰性」は$P(A^c|B_2) = 0.90$と表せます．
- $P(A^c|B_2) = 0.90$より$P(A^c|B_1) = 1 - P(A^c|B_2) = 0.10$となります．
- 日本人のうち0.01%が感染しているとしているのでこれは$P(B_1) = 0.0001$と表せます．
- 日本人のうち0.99%は感染していないということなので，これは$P(B_2) = 0.9999$と表せます．

最後に，求めたい確率はベイズの定理より

$$
  P(B_1|A) = \frac{P(B_1)P(A|B_1)}{P(B_1)P(A|B_1) + P(B_2)P(A|B_2)}
$$
となるのでこれを計算すれば，

$$
  P(B_1|A) = \frac{0.0001 \times 0.95}{0.0001 \times 0.95 + 0.9999 \times 0.05} \simeq 0.00189
$$

となり，0.2%程度であることが分かりました．

:::

このようにして病気の検査に求められる精度や，そもそもどんな人に対して検査すべきか等を適切に考慮しなければ本来感染していない人を感染していると勘違いしてしまう可能性が高いことがわかると思います．


::: {.exercise name="検査の誤判定"}

新型コロナウイルスの感染の有無を調べる検査$X$を考えましょう．この検査$X$についてはあらかじめ次のことが分かっています．

1. 実際にコロナウイルスに感染している人に対しては98%の精度で陽性となる
2. コロナウイルスに感染していない人に対しては85%の精度で陰性となる

また，日本人のうち0.03%の人がコロナウイルスに感染しているとします．このときある人が検査$X$を受けて陽性と判定されました．この人が本当にコロナウイルスに感染している確率を求めてください．

:::


::: {.exercise name="モンティホール問題"}

3つの扉があり，そのどれか一つの扉の後ろには賞金100万円が置いてあります．まずゲームの挑戦者は扉を一つだけ選びます．次に司会者が
選ばれていない2つの扉のうち，賞金が置かれていない扉を一つだけ開けます．このとき，挑戦者は残った二つの扉のうちどちらを選ぶ一度だけ選び直すことができます．さて，挑戦者は元の扉を選ぶか，またはもう一方の扉を選ぶかどちらの方が賞金を手にする確率が高いでしょうか．それぞれの確率を求めた上で答えてください．
．
:::