# 集合  

集合の言葉に慣れると，数学的な説明がよりわかりやすくかつシンプルに理解できるようになります．ここでは言葉として「集合」を扱うことに慣れるために種々の概念を紹介していきます．

## 集合の定義  

集合とは「ものの集まり」です．この「もの」は基本的にどんなものでも構いません．数学では必然的に「数」を扱うことが多いですが場合によっては文字（人や果物の名前など）の場合もあるでしょう．
また関数や集合そのものも集まりの対象として捉えることができます．例えば，学校の「クラス」などは人の集合がある条件を満たす場合の呼び方と捉えることができるでしょう．また「家族」自体は人の集合ですが，その家族の集合も考えることができますね．そしてこの「もの」のことと要素とか元と呼びます．ここでは「要素」を採用しましょう．

::: {.definition name="集合"}
集合とは要素の集まりです．要素はどんなものでも構いませんが，どんな要素と集合を考えてもその要素が集合に含まれるのか，含まれないのかは常にどちらかに決まります．ただし，集合は自身を要素には含まないものとします．
:::

各要素$x$がある集合$X$に含まれることを$x \in X$と表します．逆に含まれないことは$x \notin X$と表します．
集合の要素は常にある集合に含まれるか，含まれないかのどちらかが確定しなくてはいけません．これは集合を扱う上で重要なポイントです．つまり，ある集合$X$に対して要素$x$が$x \in X$かつ$x \notin X$どちらも成り立つということは考えません．

集合を記述する場合は各要素を$\{ \}$の中に$,$で区切って列挙します．例えば，$1$から$5$までの整数を要素に持つ集合$A$は

$$
  A = \{ 1,2,3,4,5 \}
$$

と記述します．集合の要素が多い場合は次のように省略するか，$|$で区切って要素に共通するルールを記述します．

$$
\begin{align}
  A^\prime &= \{ 1,2,\ldots,49,50 \} \\
  A^\prime &= \{ n | 1 \leq n \leq 50, n \in \N \}
\end{align}
$$

$1,2,\ldots$のように記述されている場合は，要素が無限に続いていることを意味しています．また$\N$は全ての自然数の集合を表します．

## 基本的な集合  

集合を扱う上で知っておくべき基本的な集合を紹介していきます．

::: {.example name="空集合"}
要素を１つも持たない集合を空集合と呼び，$\emptyset$と書きます．すなわちどんな要素$x$を持ってきても$x \notin \emptyset$が成り立ちます．
:::

::: {.example name="よく使われる集合"}
自然数・整数・有理数・実数についてそれぞれ全体のなす集合を表す記号を定義します．これらはよく使われるので是非覚えてください．

|集合|記号|
|:-|:-|
|自然数|$\N$|
|整数|$\Z$|
|正の整数|$\Z^{+}$|
|負の整数|$\Z^{-}$|
|有理数|$\Q$|
|実数|$\R$|

:::

::: {.example name="実数の区間"}
実数の区間は中学，高校の数学で扱ったと思います．これも集合の言葉で言えば実数の集合です．すなわち$a,b \in \R$で$a < b$のとき，$a$以上$b$以下である全ての実数のなす集合を$[a,b]$と表します．これを閉区間ともよびます．これは次のように記述することもできます．

$$
[a,b] = \{ x : x \in \R, a \leq x \leq b \}
$$

また，$a$より大きく$b$より小さい全ての実数のなす集合を$(a,b)$と表し，これを開区間とよびます．これは次のように記述できます．

$$
(a,b) = \{ x : x \in \R, a < x < b \}
$$

これらを組み合わせて，$a \leq x < b$といった条件の集合を考えることもでき，これを半開区間と呼んだりします．また無限大を表す$\infty$を使って

$$
(a, \infty) = \{ x : x \in \R, a < x \}
$$

$$
(-\infty, b) = \{ x : x \in \R, x < b \}
$$

という集合を記述することもできます．ここで，無限大はある特定の数を意味しないので$[-\infty,\infty]$のようには表さないことに注意してください．

:::

## 集合の要素に関する記号  

ある要素$x$が集合$X$に含まれることを$x \in X$と記述しましたが，ある集合$X$の要素$x$について述べる時，それが$X$に含まれるどんな要素でも良いのか，特定の要素の場合だけを考えるかの２つの場合があります．
そのような場合に便利な記法があるので紹介します．

::: {.definition name="全称記号と存在記号"}
$X$に含まれる任意の要素であることを

$$
{}^\forall x \in X
$$

と表します．また，そのような要素$x$が少なくとも一つは存在することを

$$
{}^\exists x \in X
$$

と表します．
:::

例えば，自明ですが$A = \{x:x \in \N, x \leq 50 \}$については，${}^\forall a \in A$に対して$a \leq 50$が成り立ちます．一方$a \leq 10$という条件は任意の$A$の要素について成り立つわけではありませんが少なくとも１つはそのような要素は存在するわけですから，${}^\exists x \in A$で$a \leq 10$が成り立ちます．

## 部分集合と包含関係  

集合と集合の関係で最も基本的なもので**包含関係**が挙げられます．すなわち，一方の集合が他方に含まれているかどうかです．

::: {.definition name="部分集合と包含関係"}
集合$A,B$について，${}^\forall a \in A$が$a \in B$であるとき，$B$は$A$を包含する，または含むといいます．
$B$が$A$を含む時，$A$は$B$の部分集合であるといい$A \subset B$と表します．
:::

次に，集合についての等号（$=$）について次のように定義します．

::: {.definition name="集合の等号成立"}
集合$A,B$について，$A \subset B$かつ$B \subset A$が成り立つ時，集合$A$と$B$は等しいといい$A = B$と表します．
また，集合$A$と$B$が等しくないとき$A \neq B$と表します．
:::

最後に真部分集合について次のように定義しておきます．

::: {.definition name="真部分集合"}
集合$A,B$について$A \subset B$かつ$A \neq B$が成り立つ時，$A$は$B$の真部分集合であるといいます．
:::

::: {.example}
集合$A, B, C$をそれぞれ次のように定義します．

$$
\begin{aligned}
  A &= \{ 1,2,3,4 \} \\
  B &= \{ 1,2,3,4,5 \} \\
  C &= \{ 4,3,2,1 \}
\end{aligned}
$$

このとき，$A \subset B$と$A \subset C$両方成り立っていますが，$A$は$B$の真部分集合である一方，$A$は$C$の真部分集合ではありません．
:::

::: {.exercise}
次の３つの集合について真部分集合を一つあげてください．

1. $\N$
1. $\R$
1. $\Q$

:::

## 冪（べき）集合  

ある集合$A$に対して，その部分集合を元とする集合を考えることができます．特に部分集合全体のなす集合はよく扱われます．そこで，このような集合を**冪（べき）集合**と呼び次のように定義します．

::: {.definition name="冪（べき）集合"}
集合$A$に対して，その部分集合の全体のなす集合を$A$の冪集合と呼び，$2^A$と書きます．すなわち

$$
2^A = \{ X : X \subset A \}
$$

です．
:::

冪集合の「冪」は冪乗から来ているが，$2^A$と表すのは部分集合全体が$A$に含まれる全ての要素がそれぞれ含まれるか含まれないかの２通りの組み合わせで表せることから来ています．
また，冪集合のように集合を元とする集合のことを**集合族**とよび明確に集合と分ける流儀もあります．

::: {.example name="冪集合の例"}
集合$A = \{1,2,3\}$について，その冪集合$2^A$は次のようになります．

$$
2^A = \{ \emptyset, \{ 1 \}, \{ 2 \}, \{ 3 \},\{ 1,2 \}, \{ 2,3 \}, \{ 1,3 \}, \{ 1,2,3 \} \}
$$
:::

::: {.exercise}
集合$A = \{ a,b,c,d,e,f \}$について，その冪集合の要素がいくつになるか計算してください．
:::

## 集合の演算　　

既にいくつか集合同士の関係を記述する記号を紹介しましたが，ここでは集合同士の**演算**を定義していきます．

::: {.definition name="共通部分と和集合"}
集合$A,B$について，$x \in A$かつ$x \in B$であるような要素$x$全体のなす集合を$A$と$B$の共通部分・共通集合とよび$A \cap B$と書きます．
すなわち

$$
A \cap B = \{x:x \in A \hspace{3mm}  \rm{and} \hspace{3mm} x \in B \}
$$

です．また，$y \in A$または$y \in B$であるような要素$y$全体のなす集合を和集合と呼び$A \cup B$と書きます．すなわち
$$
A \cup B = \{x:x \in A \hspace{3mm} \rm{or} \hspace{3mm} x \in B \}
$$
です．
:::

つぎに，引き算にあたる**差集合**を次のように定義します．

::: {.definition name="差集合"}
集合$A,B$について，$x \in A$かつ$x \notin B$であるような要素$x$全体のなす集合を$A \mysetminus B$と表します．
:::

差集合と定義は似ていますが，補集合を次のように定義します．

::: {.definition name="補集合"}
ある集合$\Omega$を興味の対象である要素全てを含む集合，すなわち全体集合とするとき，$A \subset \Omega$であるような集合$A$について，
$\Omega \mysetminus A$を$A$の補集合といいます．これを$A^c$と表します．すなわち

$$
A^c = \Omega \mysetminus A = \{x:x \in \Omega, x \notin A \}
$$

です．
:::

共通部分や和集合については，演算の順番によらず結果は同じになりますが，差集合については演算の順番により結果が変わることに注意してください．
実際，$A = \{ 1,3,5,6 \}$，$B = \{ 1,2,3 \}$とすると

$$
\begin{aligned}
  A \mysetminus B &= \{ 5,6 \} \\
  B \mysetminus A &= \{ 2 \}
\end{aligned}
$$

となります．

包含関係と補集合について次の定理が成り立ちます．

::: {.theorem}
全体集合$\Omega$とその部分集合$A,B$について，$A \in B$ならば$B^c \in A^c$が成り立ちます．
:::

これはベン図を用いればすぐにわかるでしょう．

::: {.theorem name="ド・モルガンの法則"}
全体集合$\Omega$とその部分集合$A,B$について，$(A \cap B)^c = A^c \cup B^c$が成り立ちます．
また，$(A \cup B)^c = A^c \cap B^c$も成り立ちます．
:::

証明は割愛します．

### 添字集合

共通部分$\cap$と和集合$\cup$を有限個の集合に対する演算に拡張します．いま$n$個の集合があるとして，それらを$A_1, A_2, \ldots, A_n$と表すことにしましょう．この時$A$の左下についている文字（ここでは数字）を**添字（そえじ）**と呼びます．そして，集合族$\mathcal A = \{ A_1, A_2, \ldots, A_n \}$を考えましょう．このとき添字の集合$I = \{ 1,2,\ldots,n \}$をそのまま集合族$\mathcal A$の添字集合と呼びます．添字集合を用いることで，要素の多い集合や集合族の記述が簡単になります．

例えば，$\mathcal A = \{ A_i : i \in I \}$で$I = \{i:i \in \N, i <= n \}$とかけます．

添字集合は数字でなくでも$a,b,c$のようなものでも良いですしもっと複雑なものでも構いません．これはあくまで要素を区別するための記号です．記述のしやすさという観点でみれば，自然数を使うのが良いでしょう．また，添字集合の要素は有限個でも無限個でも構いません．書き方として，$\{ x_i \}_{i \in \N}$のように添字集合の定義をそのまま左下に記述するケースもありますし，より明白な場合は${x_s}_{0 \leq s \leq 1}$などと略す書き方もあります．

### 集合族に対する演算  

集合族について，共通部分と和集合の演算を次のように定義します．

::: {.definition name="集合族の共通部分と和集合"}
集合族$\mathcal A = \{A_i\}_{i \in I}$について，その共通部分を

$$
\bigcap_{i \in I} A_i = \{ x: {}^\forall i \in I, x \in A_i \}
$$

と定義します．同様にその和集合を

$$
\bigcup_{i \in I} A_i = \{ x: {}^\exists i \in I, x \in A_i \}
$$

と定義します．

:::

この記号については，$\sum_{i=1}^{n}$と同じように表記されることもあります．

$$
\bigcap_{i=1}^{n} A_i, \  \bigcap_{i=1}^{\infty} A_i, \  \bigcup_{i=1}^{n} A_i, \  \bigcup_{i=1}^{\infty} A_i
$$

さらに，集合族の和集合の特別な場合として**直和**の概念を定義しておきます．

::: {.definition name="集合の分割と直和"}
集合族$\mathcal A$の和集合$A = \bigcup_{i \in I} A_i$について，どの相異なる２つの集合$A_j, A_k(j \neq k)$についても$A_j \cap A_k = \emptyset$となるとき，その和集合$A$は$\{ A_i \}_{i \in I}$で分割されているといいます．また逆に，$A$は$\{ A_i \}_{i \in I}$らの直和であるといいます．

このことを記号を用いて
$$
\bigsqcup_{i \in I} A_i
$$

と表します．他にも，$A_1 \sqcup \cdots \sqcup A_n$のように列挙して表すこともあります．
:::

典型的な例を以下に示します．

::: {.example name="無限個の区間の共通部分と和集合" #ex-infty-intersection-and-union}
$n \in \N$について，実数の区間$A_n = [0, 1/n]$を考えます．このような集合全体のなす集合族$\{ A_n \}_{n \in \N}$について

$$
\bigcap_{n \in \N} A_n = \bigcap_{n \in \N} [0, 1/n] = \{ 0 \}
$$

となります．また

$$
\bigcup_{n \in \N} = [0, 1]
$$

も成り立ちます．
:::

::: {.exercise}
例\@ref(exm:ex-infty-intersection-and-union)を確かめてください．
:::

最後にド・モルガンの法則の集合族版を以下に紹介します．

:::{.theorem name="ド・モルガンの法則"}
集合族$\mathcal A$について，以下が成り立ちます．

$$
\begin{aligned}
\left( \bigcap_{i \in I} A_i \right)^c &= \bigcup_{i \in I} A_i^c \\
\left( \bigcup_{i \in I} A_i \right)^c &= \bigcap_{i \in I} A_i^c
\end{aligned}
$$
:::




# 命題   

「命題」とは真偽のどちらか一方のみが成立するものを指します．例えば

* $100$より大きな自然数が存在する
* $57$は素数である

などはそれぞれ真偽のどちらか一方は成立し，他方は不成立となるのでこれは命題です．しかし

* あの人は男である  

といったものは命題ではありません（身体的には男性だが性自認は女性というケースもある）．

## 命題の組み合わせ  

命題の組み合わせ方は以下の４つに限られます．ここで$P, Q$をそれぞれ命題として

1. $\neg P$:$P$でない
2. $P \land Q$:$P$かつ$Q$
3. $P \lor Q$:$P$または$Q$
4. $P \Rightarrow Q$:$P$ならば$Q$

です．これらを幾度も繰り返して複雑な命題を作ることもできます．
便宜上，$P \Leftrightarrow Q$は$(P \Rightarrow Q) \land (Q \Rightarrow P)$を意味する記号として良く使われます．

## 十分条件と必要条件  

$P \Rightarrow Q$が成立するとき，$P$は$Q$の十分条件，$Q$は$P$の必要条件と言います．また
$P \Leftrightarrow Q$であるとき，$P$と$Q$は互いに必要十分条件である，と言います．


::: {.exercise}
命題$P_1, P_2, P_3$に対して次の命題を翻訳してください．

$$
((\neg P_1) \land P_2) \lor (P_3 \Rightarrow (P_1 \lor P_2))
$$
:::

## 真偽値表  

命題の操作を簡潔にまとめた表を以下に示しておきます．ここで$T$は真，$F$は偽を表します．

|$P$|$Q$|$\neg P$|$P \land Q$|$P \lor Q$|$P \Rightarrow Q$|$P \Leftrightarrow Q$|
|:-:|:-:|:-:     |:-:        |:-:       |:-:              |:-:                  |
|$T$|$T$|$F$|$T$|$T$|$T$|$T$|
|$T$|$F$|$F$|$F$|$T$|$F$|$F$|
|$F$|$T$|$T$|$F$|$T$|$T$|$F$|
|$F$|$F$|$T$|$F$|$F$|$T$|$T$|


## 恒真命題と同値な命題  

::: {.definition name="恒真命題"}
有限個の命題$P_1, \ldots, P_n$と命題の組み合わせによって作られた命題$P$を$P(P_1,\ldots,P_n)$と表します．
このとき，命題$P(P_1,\ldots,P_n)$が各命題$P_1,\ldots,P_n$の真偽によらず常に真であるとき，$P$は恒真命題であるといいます．
また，トートロジーであるいう場合もあります．
:::

::: {.example}
命題$P$に対して，$P \Rightarrow P$という命題は恒真命題です．
:::

::: {.example name="排中律"}
命題$P$に対して，命題$P \lor (\neg P)$は恒真命題です．この恒真命題を排中律といいます．
:::

::: {.definition name="同値な命題"}
有限個の命題$P_1, \ldots, P_n$から作られた２つの命題$P(P_1,\ldots,P_n)$と$Q(P_1,\ldots,P_n)$について，命題$P \Leftrightarrow Q$が恒真命題であるとき，この２つの命題は同値であるといい，$P \equiv Q$と表します．
:::

これより，命題$P,Q$が同値であればどちらか一方の真偽を調べることで他方の真偽を確認できます．数学の証明などでよく使われるテクニックを紹介しましょう．

::: {.example name="背理法"}
どんな命題$P$の真偽も命題$\neg(\neg P)$と一致します．すなわち，$P \equiv \neg(\neg P)$
:::

背理法は，証明したい命題$P$の否定の命題$\neg P$を考察していき，この命題を評価することで最終的に$P$を確かめる方法です．

::: {.example name="対偶"}
どんな２つの命題$P,Q$に対しても，命題$P \Rightarrow Q$と命題$(\neg Q) \Rightarrow (\neg P)$の真偽は一致します．これを対偶といいます．
:::

命題によっては対偶を考えることで証明がより簡単に行える場合があります．

## 全称命題と存在命題  

### 集合と命題関数  

集合の表し方について改めて考えていきましょう．ある集合$\Omega$に対して$x \in \Omega$を含む主張$P(x)$が，各$x$に対して命題であるとき，$\Omega$上の条件と呼びましょう．このとき，条件$P(x)$が真であるような$x \in \Omega$の集まりで$\Omega$の部分集合$P$を構成できます．これを$P=\{ x \in \Omega:P(x) \}$と書きます．

このように考えると，集合に関する演算と命題の結合を以下のように対応させることができます．

いま，条件$P(x), Q(x)$で定まる集合$P= \{ x \in \Omega:P(X) \}$，$Q=\{ x \in \Omega:Q(X) \}$について，

$$
\begin{aligned}
P \cap Q &= \{ x \in \Omega: P(x) \land Q(x) \} \\
P \cup Q &= \{ x \in \Omega: P(x) \lor Q(x) \} \\
P^c &= \{ x \in \Omega: \neg P(x) \}
\end{aligned}
$$

となります．

### 全称命題と存在命題

前項で言及した全称記号と存在記号を用いて全称命題と存在命題を次のように定義します．

::: {.definition name="全称命題と存在命題"}
集合$\Omega$上の条件$P(x)$に対して，「${}^\forall x \in \Omega$について$P(x)$は真である」という主張を全称命題と呼びます．これを

$$
{}^\forall x \in \Omega, P(X)
$$

と書き．同じように「${}^\exists x \in \Omega$について$P(x)$は真である」という主張を存在命題と呼び

$$
{}^\exists x \in \Omega, P(x)
$$

と書きます．
:::

また，$\rm s.t.$を使って「${}^\exists x \in \Omega \ \rm{s.t.} \  P(x)$」のように表すこともあります．

### 存在記号と一意な存在  

存在記号$\exists$は，条件を満たすものが少なくとも１つは存在することを主張しているだけで，具体的にそれがどんなものであるか，またそれがいくつあるかは言及しません．一方で，命題によっては条件を満たすものが唯一存在することを主張する場合もあります．そのような場合は「存在が一意である」，「一意に存在する」，「唯一つに定まる」などと表現します．一意に存在することを記号で$\exists 1$や$\exists !$などと表すこともあります．


### 全称命題と存在命題の例  

全称命題と存在命題の概念に慣れることは，数学の言葉を理解するのに大いに役立ちます．ここではいくつか例を紹介します．

::: {.example name="いくらでも大きい"}
「条件$P(x)$を満たす，いくらでも大きな自然数$n$が存在する」

という形の主張があります．例えば，「いくらでも大きな素数がある」などが挙げられます．これを厳密に述べるために，次のように表現します．  

「どんな自然数$N$に対しても，それより大きい$n$が存在して，条件$P(x)$を満たす．」

これを記号で書けば

$$
{}^\forall N \in \N, {}^\exists n \in \N, \hspace{3mm} \rm{s.t.} \hspace{3mm} (n > N) \land P(n).
$$

とできます．
:::

::: {.example name="十分大きい"}
「十分に大きい自然数$n$について条件$P(x)$が成り立つ」というタイプの主張があります．例えば「十分に大きい自然数$n$について，$100n < n^2$が成り立つ」と言ったものです．これは，具体的にどこからかについては言及しないが，そこから先の自然数については常に成立していることを意味しています．この「十分に大きい」をもっと厳密に述べると

「ある自然数$N$に対して，それよりも大きいどんな$n$についても，条件$P(n)$を満たす」となります．これを記号で書くと

$$
{}^\exists N \in \N, {}^\forall n \in \N, \hspace{3mm} \rm{s.t.} \hspace{3mm} (n > N) \land P(n).
$$

となります．

:::

::: {.example name="単位元の存在"}
「自然数$e$が存在して，どんな自然数$n$に対しても積$en$の結果が$n$になる」ということを記号で書けば

$$
{}^\exists e \in \N, {}^\forall n \in \N, ne=n.
$$

となります．
:::


:::{.example name="逆元の存在"}
「どんな自然数$n$に対しても，$n$との積の結果が$1$になるような数$p$（自然数とは限らない）」が存在する」これを記号で書けば

$$
{}^\forall n \in \N, {}^\exists p \in \Omega, np=1.
$$

実際，$n$に対して$p = 1/n$を取れば成り立ちます．
:::